### ISSUE TITLE
Add Hashicorp

### ISSUE THREAD

**Issue by thumperward** [ShadowJonathan/nostalebots.xyz#12]
While moving away from actually being open source, Hashicorp's products still use GitHub and they routinely lock issues after 30 days (indeed vagrant's docs even [regard this ](https://github.com/hashicorp/vagrant/blob/main/.github/CONTRIBUTING.md#issue-lifecycle) as a feature).

**Comment by ShadowJonathan** [comment]
Ah I see: [`lock-threads`](https://github.com/dessant/lock-threads) is a github action that locks *closed* issues and PRs, this is to prevent necrobumping, and imo falls entirely outside of the woes, since they just want to drive discussion and such to opened issues, and treat closed issues as properly closed (which is understandable)

I'm gonna close it as that, since I don't see any mention of a stale bot in the vagrant repo, or in any other repo, do prod me if im wrong though.
